# date: [2025-07-07 Mon]
#
# In contrast to the checks by code reformatter Black, the setup of this
# git-precommit hook does not prevent a Python script to enter the commit
# history even if flake8 identifies an issue (`--exit-zero`).  To use
# this hook, resolve the dependencies (see `requirements-dev.txt`) and
# update `.git/hooks/` by the command `pre-commit install`.
#
# Notes:
#
# - the installation creates the local folder `~/.cache/pre-commit` in
#   addition of the virtual environment you explicitly set up
# - while editing the Python scripts, `pre-commit run --all-files` allows
#   to launch the tests separately and prior to e.g., `git add *.py`
# - if necessary, `git commit -m "commit message" --no-verify` allows to
#   bypass the tests altogether.

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: "flake8 (advisory only, it does not block a commit)"
        args:
          - --exclude=.*/site-packages/.*
          - --filename=.*\.py
          - --max-line-length=90
          - --show-source
          - --statistics
          - --count
          - --exit-zero
        verbose: true
        always_run: true
