

* Background
   
   The Bemis-Murcko scaffold [1] provided by DataWarrior [2] retains
   information about bond order and chirality.  There are instances
   where retaining only information about which atoms are connected
   with each other, but not their bond order is desired.  This
   corresponds to the assumption 'there are only single bonds'.
   DataWarrior equally offers the export of Bemis-Murcko skeleton,
   however this simplifies e.g. an imidazole scaffold into
   cyclopentane.

* Typical use

   The script is to be used on the CLI of Python (either branch 2
   or 3) with the mandatory parameter about listing file containing
   the SMILES to work with:
   #+BEGIN_SRC shell
     python MurckoScaffold_bondOrder_one [listing_file.txt]
   #+END_SRC
   to generate saturated_Murcko_scaffold.csv as permanent record.

* Example

   The Bemis-Murcko scaffolds of a collection of organic materials was
   extracted with DataWarrior, leading to the listing of
   =Murcko_scaffolds_with_bond_order.txt=.

   Their graphic representation was generated by pasting the SMILES
   codes into the GUI of openbabel [3], requesting the output as
   =.svg=.  To ease the visual inspection, the option "Append input
   index to title" was activated.  Further, the default image size
   (300) was replaced by the instruction to plot an array of 12 rows
   with up to 10 columns each.  This has the advantage that the output
   may be processed further (e.g., with inkscape [4]) to generate
   either a resolution independent =.pdf= (more suitable for print) or
   =.png= (sometimes more suitable for a visual inspection on screen).

   By call of
   #+BEGIN_SRC shell
     python MurckoScaffold_bondOrder_one Murcko_scaffolds_with_bond_order.txt
   #+END_SRC
   the new listing, =saturated_Murcko_scaffold.csv= was obtained.  Its
   results were processed with =openbabel= as mentioned above.

   As desired, this "artificial saturation" of double / triple /
   aromatic bonds retains the information about which atoms are
   directly connected with each other.  =openbabel='s algorithm to
   display the molecular structures sometimes deals surprisingly well
   complicated entries (e.g., the cyclophane in #33).  There are other
   cases (#38, 50, 110) where only an inspection of the SMILES and the
   3D regeneration in a sketcher reveals their "true nature" (e.g.,
   motif of sparteine, or adamantane).


[1] Bemis GW, Murcko MA J. Med. Chem. 1996, 39, 2887-2893,
    doi 10.1021/jm9602928
    
[2] Sander T, Freyss J, von Korff M, Rufener C, J. Chem. Inf. Model. 2015,
    55, 460-473, doi 10.1021/ci500588j, [[http://www.openmolecules.org]]
    
[3] [[www.openbabel.org]]

[4] https://inkscape.org
