name: CI_pytest_datawarrior_saturate_murcko_scaffolds

# name    : pytest.yml
# purpose : regularly run pytest on the saturator script
# date    : [2024-03-21 Thu]
# edit    : [2025-07-21 Mon]

on:
  push:
    branches:
      - main             # updates to enter the principal branch "main"
      - dev
  pull_request:
    branches:
      - main             # PRs to enter the principal branch "main"
  workflow_dispatch:     # provide a manual trigger
  schedule:
    - cron: "0 0 1 * *"  # once each 1st of a month, at 00:00 UTC (cf. https://crontab.guru/)

jobs:
  test:
    strategy:
      matrix:
        # for a factorial test, an explicit selection of GitHub runner images
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        # state of commit 4bd4d1b as visited on 2025-07-07 Mon
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}

    timeout-minutes: 3  # Timeout for each job individually

    steps:
      - uses: actions/checkout@v4
        # by [2024-10-23 Wed], this version possibly will be considered "old", cf.
        # https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with PyPI
        run: pip install pytest

      - name: Run the check with pytest
        run: python -m pytest

